<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

        <div class="col-lg-12">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <strong>密码:</strong> 新建管理员默认密码为:<?=DEFAULT_USER_PASS?>
            </div>
            <div class="ibox float-e-margins">
                <div class="ibox-content">

                        <?=$this->Bootstrap3Horizontal($this->form);?>

                </div>
            </div>
        </div>
    </div>


</div>

