<?php
/**
 * Created by PhpStorm.
 * User: denny
 * Date: 2017/5/14
 * Time: 15:38
 */

namespace Main\Controller\User;


use Zend\Mvc\Controller\AbstractActionController;

class CenterController extends AbstractActionController
{

    function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }


}