<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <?= $this->headTitle('denny博客后台管理')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headLink()
        ->prependStylesheet($this->basePath('style/admin/css/collect.css'));
    ?>

</head>

<body>
<?php
$adminMenu=$this->adminMenuPlug();

$adminList=$adminMenu->menu();

?>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">

                        <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="/style/admin/images/profile_small.jpg" />
                             </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                                <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"><?=$this->identity()['username']?></strong>
                             </span> <span class="text-muted text-xs block"><?=$this->identity()['name']?> <b class="caret"></b></span> </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="form_avatar.html">修改头像</a>
                                </li>
                                <li><a href="profile.html">个人资料</a>
                                </li>
                                <li><a href="contacts.html">联系我们</a>
                                </li>
                                <li><a href="mailbox.html">信箱</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="login.html">安全退出</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            H+
                        </div>

                    </li>

                    <?php foreach($adminList as $val):?>
                        <li <?php if($val['status']):?>class="active"<?php endif;?>>
                            <a href="<?php if(!empty($val['router'])){echo $this->url($val['router']);}else{echo 'javascript:void(0);';}?>"><i class="<?=$val['ico'];?>"></i> <span class="nav-label"><?=$val['title'];?></span><?php if(!empty($val['parents'])):?><span class="fa arrow"></span><?php endif;?></a>
                            <?php if(!empty($val['parents'])):?>
                            <ul class="nav nav-second-level">
                            <?php foreach($val['parents'] as $v):?>
                                <li <?php if($v['status']):?>class="active"<?php endif;?>><a href="<?=$this->url($v['router']);?>"><?=$v['title'];?></a></li>
                            <?php endforeach;?>
                            </ul>
                            <?php endif;?>
                        </li>
                    <?php endforeach;?>
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="index.html#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="请输入您需要查找的内容 …" class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message"><a href="index.html" title="返回首页"><i class="fa fa-home"></i></a>欢迎使用中网科技后台管理系统</span>
                        </li>
                        <li>
                            <a href="<?=$this->url("admin/out")?>">

                                <i class="fa fa-sign-out"></i> 退出
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>
            <?=$adminMenu->breadcrum()?>
            <?=$this->flashMessenger()->render(\Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_SUCCESS,['alert','alert-success']);?>
            <?=$this->flashMessenger()->render(\Zend\Mvc\Plugin\FlashMessenger\FlashMessenger::NAMESPACE_ERROR,['alert','alert-danger']);?>
            <?= $this->content ?>
            <div class="row">
                <div class="footer">
                    <div class="pull-right">
                        By：<a href="http://www.allok.wang" target="_blank">denny's blog</a>
                    </div>
                    <div>
                        <strong>Copyright</strong> H+ &copy; 2017
                    </div>
                </div>
            </div>

        </div>
    </div>

    <?= $this->headScript()
        ->prependFile($this->basePath('style/admin/js/collect.js'));
    ?>

</body>

</html>