<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">最新文章</h3>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><span class="badge">14</span>Cras justo odio</li>
        <li class="list-group-item"><span class="badge">14</span>Dapibus ac facilisis in</li>
        <li class="list-group-item"><span class="badge">14</span>Morbi leo risus</li>
        <li class="list-group-item"><span class="badge">14</span>Porta ac consectetur ac</li>
        <li class="list-group-item"><span class="badge">14</span>Vestibulum at eros</li>
    </ul>
</div>